/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Screenshot20231020AtImage from 'src/assets/images/ContentContainer_Screenshot_2023_10_20_at_9_12_1.png';
import { styled } from '@mui/material/styles';

const PageFlowchart = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: '100%',
  width: '100%',
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Screenshot20231020At = styled('img')({
  height: `498px`,
  width: `765px`,
  objectFit: `cover`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
});

function ContentContainer(props) {
  return (
    <PageFlowchart className={props.className}>
      <Screenshot20231020At
        src={Screenshot20231020AtImage}
        loading="lazy"
        alt={'Screenshot 2023-10-20 at 9.12 1'}
      />
    </PageFlowchart>
  );
}

export default ContentContainer;
