/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector.png';
import Vector1Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_1.png';
import Vector2Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_2.png';
import Vector3Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_3.png';
import Vector4Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_4.png';
import Vector5Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_5.png';
import Vector6Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_6.png';
import Vector7Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_7.png';
import Vector8Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_8.png';
import Vector9Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_9.png';
import Vector10Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_10.png';
import Vector11Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_11.png';
import Vector12Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_12.png';
import Vector13Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_13.png';
import Search24PxImage from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_search_24px.svg';
import Chat24PxImage from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_chat_24px.svg';
import Settings24PxImage from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_settings_24px.svg';
import Vector91Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Vector_9_1.png';
import ArrowLeftImage from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Arrow_left.png';
import { styled } from '@mui/material/styles';
import Balance4Image from 'src/assets/images/HomeBudgetsAlliPadPro11Landscape_Balance.png';
import Q4SubcomponentsTilesAccountAcc from 'src/components/Q4SubcomponentsTilesAccountAcc/Q4SubcomponentsTilesAccountAcc';

const HomeBudgetsAllIPadPr1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `834px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Container = styled('div')({
  opacity: `0.800000011920929`,
  background: `linear-gradient(106deg, rgba(153, 153, 153, 1) 3.198744666291348%, rgba(232, 232, 232, 1) 93.36067607829887%)`,
  borderRadius: `0px`,
  width: `1194px`,
  height: `834px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const MinimizedSidebarNav = styled('div')({
  opacity: `0.4000000059604645`,
  backgroundColor: `rgba(0, 0, 0, 1)`,
  borderRadius: `0px`,
  width: `80px`,
  height: `960px`,
  position: `absolute`,
  left: `0px`,
  top: `64px`,
});

const QuickActions = styled('div')({
  backdropFilter: `blur(200px)`,
  WebkitBackdropFilter: `blur(200px)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `60px 24px`,
  boxSizing: `border-box`,
  width: `80px`,
  height: `834px`,
  left: `0px`,
  top: `0px`,
});

const Q19 = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `34px`,
  width: `34px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Group = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `35.76px`,
  height: `44.09px`,
  left: `-2px`,
  top: `0px`,
});

const Vector = styled('img')({
  height: `34px`,
  width: `34px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Group1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `17.55px`,
  height: `29.22px`,
  left: `9px`,
  top: `7px`,
});

const Vector1 = styled('img')({
  height: `5.31px`,
  width: `5.31px`,
  position: `absolute`,
  left: `0px`,
  top: `10px`,
});

const Vector2 = styled('img')({
  height: `14.34px`,
  width: `9.03px`,
  position: `absolute`,
  left: `3px`,
  top: `15px`,
});

const Vector3 = styled('img')({
  height: `11.37px`,
  width: `8.6px`,
  position: `absolute`,
  left: `3px`,
  top: `13px`,
});

const Vector4 = styled('img')({
  height: `23.11px`,
  width: `15.77px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Vector5 = styled('img')({
  height: `1.06px`,
  width: `1.59px`,
  position: `absolute`,
  left: `12px`,
  top: `15px`,
});

const Group2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `21.25px`,
  height: `12.22px`,
  left: `5px`,
  top: `32px`,
});

const Vector6 = styled('img')({
  height: `12.22px`,
  width: `21.25px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `28.32px`,
  height: `22.96px`,
  left: `0px`,
  top: `4px`,
});

const Vector7 = styled('img')({
  height: `19.49px`,
  width: `8.67px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector8 = styled('img')({
  height: `5.65px`,
  width: `4.98px`,
  position: `absolute`,
  left: `7px`,
  top: `3px`,
});

const Vector9 = styled('img')({
  height: `22.47px`,
  width: `21.25px`,
  position: `absolute`,
  left: `7px`,
  top: `0px`,
});

const Vector10 = styled('img')({
  height: `2.13px`,
  width: `1.59px`,
  position: `absolute`,
  left: `18px`,
  top: `19px`,
});

const Vector11 = styled('img')({
  height: `2.13px`,
  width: `1.59px`,
  position: `absolute`,
  left: `23px`,
  top: `19px`,
});

const Group4 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `12.22px`,
  height: `1.59px`,
  left: `15px`,
  top: `21px`,
});

const Vector12 = styled('img')({
  height: `1.59px`,
  width: `2.66px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector13 = styled('img')({
  height: `1.59px`,
  width: `2.13px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Search24Px = styled('img')({
  height: `auto`,
  width: `34px`,
  margin: `60px 0px 0px 0px`,
});

const Chat24Px = styled('img')({
  height: `auto`,
  width: `34px`,
  margin: `60px 0px 0px 0px`,
});

const Settings24Px = styled('img')({
  height: `auto`,
  width: `34px`,
  margin: `60px 0px 0px 0px`,
});

const SecondaryPanel = styled('div')({
  backdropFilter: `blur(30px)`,
  WebkitBackdropFilter: `blur(30px)`,
  border: `1px solid rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  width: `564px`,
  height: `834px`,
  position: `absolute`,
  left: `630px`,
  top: `0px`,
});

const MainPanelAccountsAll = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `60px 40px`,
  boxSizing: `border-box`,
  height: `728px`,
  left: `80px`,
  top: `0px`,
});

const AccountSummaryPanel = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.85)`,
  borderRadius: `40px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `30px 40px 40px 40px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const Balance = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
});

const AccountSummary = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 5px 0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Group289416 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `510px`,
  height: `30px`,
  margin: `0px`,
});

const Group289391 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `510px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const Group289369 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `510px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const Text = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.8)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `-0.4099999964237213px`,
  textDecoration: `none`,
  lineHeight: `120.00000476837158%`,
  textTransform: `none`,
  width: `510px`,
  height: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Balance1 = styled('div')({
  backgroundColor: `rgba(36, 36, 36, 1)`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `12px 0px 0px 0px`,
  overflow: `hidden`,
});

const AccountSummary1 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `20px 24px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
});

const Q4SubcomponentsTiles = styled(Q4SubcomponentsTilesAccountAcc)(
  ({ theme }) => ({
    width: `311px`,
    margin: `0px`,
  })
);

const Q4SubcomponentsTiles1 = styled(Q4SubcomponentsTilesAccountAcc)(
  ({ theme }) => ({
    width: `311px`,
    margin: `5px 0px 0px 0px`,
  })
);

const Frame14363 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `260px`,
  top: `63px`,
});

const MyWallet = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame14336 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `16px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `8px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 8px`,
}));

const ArrowRight = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `16px`,
  height: `16px`,
  margin: `0px`,
});

const Vector91 = styled('img')({
  height: `8px`,
  width: `10px`,
  position: `absolute`,
  left: `23px`,
  top: `12px`,
});

const Balance2 = styled('div')({
  backgroundColor: `rgba(109, 109, 109, 1)`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `12px 0px 0px 0px`,
  overflow: `hidden`,
});

const AccountSummary2 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `20px 24px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
});

const Q4SubcomponentsTiles2 = styled(Q4SubcomponentsTilesAccountAcc)(
  ({ theme }) => ({
    width: `311px`,
    margin: `0px`,
  })
);

const Q4SubcomponentsTiles3 = styled(Q4SubcomponentsTilesAccountAcc)(
  ({ theme }) => ({
    width: `311px`,
    margin: `5px 0px 0px 0px`,
  })
);

const Stat = styled('div')({
  borderRadius: `9px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `12px 0px 0px 0px`,
  overflow: `hidden`,
});

const Frame14368 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `9px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `12px 24px`,
  width: `390px`,
  margin: `0px`,
});

const Frame14367 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const ArrowLeft = styled('img')({
  height: `24px`,
  width: `24px`,
  margin: `0px`,
});

const Frame14277 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 12px`,
});

const ExpensesToDate = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.5)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `500`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  margin: `0px`,
});

const Q3276 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 37, 37, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `600`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `135.0000023841858%`,
  textTransform: `none`,
  margin: `0px`,
}));

const SecondaryPanelTools = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `60px 40px`,
  boxSizing: `border-box`,
  height: `667px`,
  left: `630px`,
  top: `0px`,
});

const HouseholdHarmonyCta = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.85)`,
  borderRadius: `40px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `30px 40px 40px 40px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const Balance3 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
});

const AccountSummary3 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 5px 0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Group2894161 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  height: `30px`,
  margin: `0px`,
});

const Group2893911 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const Group2893691 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const Text1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.8)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `-0.4099999964237213px`,
  textDecoration: `none`,
  lineHeight: `120.00000476837158%`,
  textTransform: `none`,
  width: `390px`,
  height: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Balance4 = styled('div')({
  backgroundImage: `url(${Balance4Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `430px`,
  width: `390px`,
  margin: `12px 0px 0px 0px`,
  overflow: `hidden`,
});

const AccountSummary4 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `20px 24px`,
  boxSizing: `border-box`,
  height: `430px`,
  width: `390px`,
  margin: `0px`,
});

const Q4SubcomponentsTiles4 = styled(Q4SubcomponentsTilesAccountAcc)(
  ({ theme }) => ({
    width: `311px`,
    margin: `0px`,
  })
);

const Q4SubcomponentsTiles5 = styled(Q4SubcomponentsTilesAccountAcc)(
  ({ theme }) => ({
    width: `330px`,
    margin: `5px 0px 0px 0px`,
  })
);

const Q4SubcomponentsTiles6 = styled(Q4SubcomponentsTilesAccountAcc)(
  ({ theme }) => ({
    width: `340px`,
    margin: `5px 0px 0px 0px`,
  })
);

const ButtonFullWidth = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `16px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px`,
  boxSizing: `border-box`,
  height: `50px`,
  width: `340px`,
  left: `24px`,
  top: `338px`,
});

const ViewBudgets = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(48, 48, 48, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

function HomeBudgetsAllIPadPr(props) {
  return (
    <HomeBudgetsAllIPadPr1 className={props.className}>
      <Container></Container>
      {false && <MinimizedSidebarNav></MinimizedSidebarNav>}
      <QuickActions>
        <Q19>
          <Group>
            <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
            <Group1>
              <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
              <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
              <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
              <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
              <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
            </Group1>
            <Group2>
              <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
            </Group2>
            <Group3>
              <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
              <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
              <Vector9 src={Vector9Image} loading="lazy" alt={'Vector'} />
            </Group3>
            <Vector10 src={Vector10Image} loading="lazy" alt={'Vector'} />
            <Vector11 src={Vector11Image} loading="lazy" alt={'Vector'} />
            <Group4>
              <Vector12 src={Vector12Image} loading="lazy" alt={'Vector'} />
              <Vector13 src={Vector13Image} loading="lazy" alt={'Vector'} />
            </Group4>
          </Group>
        </Q19>
        <Search24Px src={Search24PxImage} loading="lazy" alt={'search_24px'} />
        <Chat24Px src={Chat24PxImage} loading="lazy" alt={'chat_24px'} />
        <Settings24Px
          src={Settings24PxImage}
          loading="lazy"
          alt={'settings_24px'}
        />
      </QuickActions>
      <SecondaryPanel></SecondaryPanel>
      <MainPanelAccountsAll>
        <AccountSummaryPanel>
          <Balance>
            <AccountSummary>
              <Group289416>
                <Group289391>
                  <Group289369>
                    <Text>{`Account Summary`}</Text>
                  </Group289369>
                </Group289391>
              </Group289416>
            </AccountSummary>
            <Balance1>
              <AccountSummary1>
                <Q4SubcomponentsTiles />
                <Q4SubcomponentsTiles1 />
                <Frame14363>
                  <MyWallet>{`My Wallet`}</MyWallet>
                  <Frame14336>
                    <ArrowRight>
                      <Vector91
                        src={Vector91Image}
                        loading="lazy"
                        alt={'Vector 9'}
                      />
                    </ArrowRight>
                  </Frame14336>
                </Frame14363>
              </AccountSummary1>
            </Balance1>
            <Balance2>
              <AccountSummary2>
                <Q4SubcomponentsTiles2 />
                <Q4SubcomponentsTiles3 />
              </AccountSummary2>
            </Balance2>
            <Stat>
              <Frame14368>
                <Frame14367>
                  <ArrowLeft
                    src={ArrowLeftImage}
                    loading="lazy"
                    alt={'Arrow_left'}
                  />
                  <Frame14277>
                    <ExpensesToDate>{`Expenses to-date`}</ExpensesToDate>
                    <Q3276>{`$ 3,276`}</Q3276>
                  </Frame14277>
                </Frame14367>
              </Frame14368>
            </Stat>
          </Balance>
        </AccountSummaryPanel>
      </MainPanelAccountsAll>
      <SecondaryPanelTools>
        <HouseholdHarmonyCta>
          <Balance3>
            <AccountSummary3>
              <Group2894161>
                <Group2893911>
                  <Group2893691>
                    <Text1>{`Tools`}</Text1>
                  </Group2893691>
                </Group2893911>
              </Group2894161>
            </AccountSummary3>
            <Balance4>
              <AccountSummary4>
                <Q4SubcomponentsTiles4 />
                <Q4SubcomponentsTiles5 />
                <Q4SubcomponentsTiles6 />
                <ButtonFullWidth>
                  <ViewBudgets>{`View Budgets`}</ViewBudgets>
                </ButtonFullWidth>
              </AccountSummary4>
            </Balance4>
          </Balance3>
        </HouseholdHarmonyCta>
      </SecondaryPanelTools>
    </HomeBudgetsAllIPadPr1>
  );
}

export default HomeBudgetsAllIPadPr;
